### ISSUE TITLE
移除idea文件夹

### ISSUE THREAD

**Issue by BlackHole1** [simple-ice/zhipin_client#1]
RT

**Comment by simple-ice** [comment]
已删除 (明明忽略了，却偷偷上传了) : )

**Comment by BlackHole1** [comment]
如果发现有不想上传的文件或文件夹被上传

需要通过.gitignore忽略后，还要删除这个文件夹，然后通过commit -am才可以。

gitignore只是为了本地git以后不会跟踪这个文件的变化
